#pragma once

enum {
	BOCHSVGA_ID = 0,
	BOCHSVGA_XRES,
	BOCHSVGA_YRES,
	BOCHSVGA_BPP,
	BOCHSVGA_ENABLED,
	BOCHSVGA_BANK,
	BOCHSVGA_WIDTH,
	BOCHSVGA_HEIGHT,
	BOCHSVGA_X_OFFSET,
	BOCHSVGA_Y_OFFSET,
};

enum {
	BOCHSVGA_BPP4 = 0x04,
	BOCHSVGA_BPP8 = 0x08,
	BOCHSVGA_BPP15 = 0x0f,
	BOCHSVGA_BPP16 = 0x10,
	BOCHSVGA_BPP24 = 0x18,
	BOCHSVGA_BPP32 = 0x20,

	BOCHSVGA_FB_ENABLED = 0x40,
	BOCHSVGA_NO_CLEAR = 0x80,
};

void bochsvga_init();