#pragma once

enum {
	SYSCALL_LINUX_NOTHING = 0, // do nothing
	SYSCALL_LINUX_EXIT, // exit
	SYSCALL_LINUX_FORK, // fork
	SYSCALL_LINUX_READ, // read fd
	SYSCALL_LINUX_WRITE, // write to fd
	SYSCALL_LINUX_OPEN, // open file
	SYSCALL_LINUX_CLOSE, // close fd
	SYSCALL_LINUX_WAITPID, // wait for process to exit
	SYSCALL_LINUX_CREAT, // create file
	SYSCALL_LINUX_LINK, // do nothing
	SYSCALL_LINUX_UNLINK, // do nothing
	SYSCALL_LINUX_EXECVE, // execute shit
	SYSCALL_LINUX_CHDIR, // change directory
	SYSCALL_LINUX_TIME, // get time
	SYSCALL_LINUX_MKNOD, // do nothing (maybe)
	SYSCALL_LINUX_CHMOD, // do nothing
	SYSCALL_LINUX_LCHOWN, // do nothing
	SYSCALL_LINUX_BREAK, // do nothing
	SYSCALL_LINUX_OLDSTAT, // do nothing
	SYSCALL_LINUX_LSEEK, // do nothing
	SYSCALL_LINUX_GETPID, // get process id
	SYSCALL_LINUX_MOUNT, // mount (possibly?)
	SYSCALL_LINUX_UMOUNT, // unmount (possibly?)
	SYSCALL_LINUX_SETUID, // set process user id
	SYSCALL_LINUX_GETUID, // get process user id
	SYSCALL_LINUX_STIME, // do nothing
	SYSCALL_LINUX_PTRACE, // do nothing
	SYSCALL_LINUX_ALARM, // trigger SIG_ALARM in n seconds
	SYSCALL_LINUX_OLDFSTAT, // do nothing
	SYSCALL_LINUX_PAUSE, // wait for signal
	SYSCALL_LINUX_UTIME, // do nothing
	SYSCALL_LINUX_STTY, // do nothing
	SYSCALL_LINUX_GTTY, // do nothing
	SYSCALL_LINUX_ACCESS, // do nothing
	SYSCALL_LINUX_NICE, // do nothing
	SYSCALL_LINUX_FTIME, // do nothing
	SYSCALL_LINUX_SYNC, // do nothing
	SYSCALL_LINUX_KILL, // send signal to process
	SYSCALL_LINUX_OLDUNAME = 59, // old uname
	SYSCALL_LINUX_GETPPID, // get parent process id
	SYSCALL_LINUX_REBOOT, // reboot
	SYSCALL_LINUX_SYSINFO = 116, // ipc
	SYSCALL_LINUX_IPC, // ipc
	SYSCALL_LINUX_CLONE = 120, // clone
	SYSCALL_LINUX_UNAME = 122, // ipc
	SYSCALL_LINUX_SCHED_YIELD = 158,
	SYSCALL_LINUX_VM86 = 166, // enter v86 mode
	SYSCALL_LINUX_PRCTL = 172,
	SYSCALL_LINUX_GETLOCALE = 222,
	SYSCALL_LINUX_GETTHERM = 223,
	SYSCALL_LINUX_LCTL = 251,
	SYSCALL_LINUX_GETRANDOM = 355,
	SYSCALL_LINUX_SOCKET = 359,
	SYSCALL_LINUX_SOCKETPAIR,
	SYSCALL_LINUX_BIND,
	SYSCALL_LINUX_CONNECT,
	SYSCALL_LINUX_LISTEN,
	SYSCALL_LINUX_ACCEPT4,
	SYSCALL_LINUX_GETSOCKOPT,
	SYSCALL_LINUX_SETSOCKOPT,
	SYSCALL_LINUX_GETSOCKNAME,
	SYSCALL_LINUX_GETPEERNAME,
	SYSCALL_LINUX_SENDTO,
	SYSCALL_LINUX_SENDMSG,
	SYSCALL_LINUX_RECVFROM,
	SYSCALL_LINUX_SHUTDOWN,
	SYSCALL_LINUX_MALLOC = 385,
	SYSCALL_LINUX_FREE = 386,
};

enum {
	PR_SET_PDEATHSIG = 1,
	PR_GET_PDEATHSIG,
	PR_GET_DUMPABLE,
	PR_SET_DUMPABLE,
	PR_GET_UNALIGN,
	PR_SET_UNALIGN,
	PR_GET_KEEPCAPS,
	PR_SET_KEEPCAPS,
	PR_GET_FPEMU,
	PR_SET_FPEMU,
	PR_GET_FPEXC,
	PR_SET_FPEXC,
	PR_GET_TIMING,
	PR_SET_TIMING,
	PR_SET_NAME,
	PR_GET_NAME,
	PR_GET_ENDIAN,
	PR_SET_ENDIAN,
	PR_GET_SECCOMP,
	PR_SET_SECCOMP,
	PR_CAPBSET_READ,
	PR_CAPBSET_DROP,
	PR_GET_TSC,
	PR_SET_TSC,
	PR_GET_SECUREBITS,
	PR_SET_SECUREBITS,
	PR_GET_ACTIVE = 7301,
	PR_SET_ACTIVE = 7302,
	PR_UNSET_ACTIVE = 7303,
	PR_GET_HANDLER = 7304,
	PR_SET_HANDLER = 7305,
	PR_UNSET_HANDLER = 7306,
	PR_HOOK_STDOUT = 7307,
};

enum {
	PR_HANDLER_GLOBAL,
	PR_HANDLER_PRIVATE,
};

enum {
	LCTL_MULTIBOOT_MAGIC = 0,
	LCTL_CPU_TYPE_MAGIC,
	LCTL_CPU_VENDOR_MAGIC,
	LCTL_PERF_STATE_MAGIC,
	LCTL_REQUEST_FRAMEBUFFER,
	LCTL_TIMER_SET_FREQUENCY,
	LCTL_TIMER_FREQUENCY,
	LCTL_TIMER_TIMESTAMP,
	LCTL_GET_LAYOUT,
	LCTL_FONT_GET_BITMAPS,
	LCTL_FONT_GET_SIZE,
	LCTL_INITRD_LOAD,
	LCTL_GET_PCB,
	LCTL_GET_PERSONALITY,
	LCTL_GET_NAMED_PERSONALITY,

	LCTL_DISPLAY_LISTEN,
	LCTL_DISPLAY_GET_DEFAULT,
	LCTL_DISPLAY_RESIZE,
	LCTL_DISPLAY_CRUNCH,
};

void personality_linux_init();