#pragma once

enum {
	VDEBUGGER_OPERATION	= 0x00,
	VDEBUGGER_IN		= 0x02,
	VDEBUGGER_OUT		= 0x03,
	VDEBUGGER_CMD		= 0x04,
	VDEBUGGER_SIZE		= 0x08,
};

enum {
	VDEBUGGER_OPERATION_NOP				= 0x00,
	VDEBUGGER_OPERATION_LOAD			= 0x01,
	VDEBUGGER_OPERATION_IDENTIFY		= 0x02,
	VDEBUGGER_OPERATION_LOG				= 0x03,
	VDEBUGGER_OPERATION_INSERT_EVENT	= 0x04,
};

enum {
	VDEBUGGER_CMD_START		= 0x01,
	VDEBUGGER_CMD_ACK		= 0x02,
	VDEBUGGER_CMD_REJECT	= 0x03,
};

void vdebugger_init();